# Generated by Django 4.2.30 on 2026-07-09 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_id', models.CharField(max_length=50, unique=True)),
                ('child_first_name', models.CharField(max_length=100)),
                ('child_last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('time_of_birth', models.TimeField(blank=True, null=True)),
                ('place_of_birth', models.CharField(max_length=200)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('father_first_name', models.CharField(max_length=100)),
                ('father_last_name', models.CharField(max_length=100)),
                ('father_date_of_birth', models.DateField(blank=True, null=True)),
                ('father_nationality', models.CharField(default='Congolaise', max_length=50)),
                ('father_profession', models.CharField(blank=True, max_length=100)),
                ('father_id_number', models.CharField(blank=True, max_length=100)),
                ('mother_first_name', models.CharField(max_length=100)),
                ('mother_last_name', models.CharField(max_length=100)),
                ('mother_date_of_birth', models.DateField(blank=True, null=True)),
                ('mother_nationality', models.CharField(default='Congolaise', max_length=50)),
                ('mother_profession', models.CharField(blank=True, max_length=100)),
                ('mother_id_number', models.CharField(blank=True, max_length=100)),
                ('doctor_name', models.CharField(max_length=200)),
                ('doctor_license', models.CharField(blank=True, max_length=100)),
                ('declaration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('approved', 'Validé'), ('rejected', 'Rejeté'), ('paid', 'Payé')], default='draft', max_length=20)),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('medical_certificate', models.FileField(blank=True, upload_to='births/medical/')),
                ('father_id_doc', models.FileField(blank=True, upload_to='births/ids/')),
                ('mother_id_doc', models.FileField(blank=True, upload_to='births/ids/')),
                ('marriage_certificate', models.FileField(blank=True, upload_to='births/marriage/')),
                ('qr_code', models.ImageField(blank=True, upload_to='births/qr/')),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'birth_certificates',
                'ordering': ['-created_at'],
            },
        ),
    ]
