# Generated by Django 4.2.30 on 2026-07-09 11:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_id', models.CharField(max_length=50, unique=True)),
                ('report_type', models.CharField(choices=[('fraud', 'Fraude / Faux certificat'), ('error', 'Erreur dans un certificat'), ('hospital', 'Probleme avec un hopital'), ('system', 'Probleme technique'), ('other', 'Autre')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Eleve'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('certificate_id', models.CharField(blank=True, max_length=50)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewed', 'Examine'), ('resolved', 'Resolu'), ('rejected', 'Rejete')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'citizen_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_id', models.CharField(max_length=50, unique=True)),
                ('report_type', models.CharField(choices=[('monthly_births', 'Rapport mensuel naissances'), ('monthly_deaths', 'Rapport mensuel deces'), ('quarterly', 'Rapport trimestriel'), ('annual', 'Rapport annuel'), ('audit', "Rapport d'audit"), ('custom', 'Rapport personnalise')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_births', models.PositiveIntegerField(default=0)),
                ('total_deaths', models.PositiveIntegerField(default=0)),
                ('male_births', models.PositiveIntegerField(default=0)),
                ('female_births', models.PositiveIntegerField(default=0)),
                ('male_deaths', models.PositiveIntegerField(default=0)),
                ('female_deaths', models.PositiveIntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
                ('pdf_file', models.FileField(blank=True, upload_to='reports/pdf/')),
                ('excel_file', models.FileField(blank=True, upload_to='reports/excel/')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('reviewed', 'Examine'), ('approved', 'Approuve'), ('rejected', 'Rejete')], default='draft', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
