# Generated by Django 4.2.30 on 2026-07-10 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenreport',
            name='mentioned_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizen_reports', to='hospitals.hospital'),
        ),
    ]
