# Generated by Django 4.2.30 on 2026-07-09 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('certificate', 'Certificat'), ('validation', 'Validation'), ('payment', 'Paiement'), ('report', 'Rapport'), ('system', 'Système'), ('alert', 'Alerte')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('related_type', models.CharField(blank=True, max_length=50)),
                ('related_id', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_new_certificate', models.BooleanField(default=True)),
                ('email_validation', models.BooleanField(default=True)),
                ('email_report', models.BooleanField(default=False)),
                ('email_daily_summary', models.BooleanField(default=True)),
                ('push_new_certificate', models.BooleanField(default=True)),
                ('push_validation', models.BooleanField(default=True)),
                ('push_urgent', models.BooleanField(default=True)),
                ('push_system', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
    ]
