# Generated by Django 4.2.30 on 2026-07-09 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('citizen', 'Citoyen'), ('hospital', 'Hôpital'), ('authority', 'Autorité')], max_length=20)),
                ('title', models.CharField(blank=True, help_text='Titre auto-généré de la conversation', max_length=255)),
                ('context_data', models.JSONField(default=dict, help_text='Données contextuelles: nom, hôpital, stats, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Question ou mot-clés')),
                ('answer', models.TextField(help_text='Réponse prédéfinie')),
                ('role', models.CharField(choices=[('citizen', 'Citoyen'), ('hospital', 'Hôpital'), ('authority', 'Autorité'), ('all', 'Tous les rôles')], default='all', max_length=20)),
                ('category', models.CharField(blank=True, help_text='Catégorie: naissance, deces, certificat, paiement, etc.', max_length=100)),
                ('keywords', models.JSONField(default=list, help_text='Mots-clés pour la recherche')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Priorité de correspondance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Utilisateur'), ('ai', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('source', models.CharField(blank=True, choices=[('faq', 'Suggestion prédéfinie'), ('groq', 'Groq Claude API'), ('hybrid', 'Mixte')], max_length=20, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Temps de réponse, tokens, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.conversation')),
                ('faq_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_assistant.faq')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
