# Generated by Django 4.2.30 on 2026-07-17 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publication_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('period_type', models.CharField(choices=[('day', 'Jour'), ('week', 'Semaine'), ('month', 'Mois'), ('year', 'Annee')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('geo_level', models.CharField(choices=[('national', 'National'), ('province', 'Province'), ('city', 'Ville'), ('commune', 'Commune')], default='national', max_length=10)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('total_births', models.PositiveIntegerField(default=0)),
                ('total_deaths', models.PositiveIntegerField(default=0)),
                ('male_births', models.PositiveIntegerField(default=0)),
                ('female_births', models.PositiveIntegerField(default=0)),
                ('male_deaths', models.PositiveIntegerField(default=0)),
                ('female_deaths', models.PositiveIntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'publications',
                'ordering': ['-published_at'],
            },
        ),
    ]
