# Generated by Django 4.2.30 on 2026-07-09 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hospital_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('official_license', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(blank=True, max_length=10)),
                ('hospital_type', models.CharField(choices=[('public', 'Public'), ('prive', 'Privé'), ('confessionnel', 'Confessionnel'), ('ong', 'ONG / Humanitaire')], default='public', max_length=20)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('pending', 'En attente de paiement')], default='pending', max_length=20)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital_logos/')),
                ('director_name', models.CharField(blank=True, max_length=200)),
                ('director_phone', models.CharField(blank=True, max_length=20)),
                ('director_email', models.EmailField(blank=True, max_length=254)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('staff_count', models.PositiveIntegerField(default=0)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('services', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('total_births', models.PositiveIntegerField(default=0)),
                ('total_deaths', models.PositiveIntegerField(default=0)),
                ('total_certificates', models.PositiveIntegerField(default=0)),
                ('validation_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('opening_fee_paid', models.BooleanField(default=False)),
                ('opening_fee_paid_at', models.DateTimeField(blank=True, null=True)),
                ('opening_fee_amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('subscription_plan', models.CharField(blank=True, max_length=20)),
                ('subscription_expiry', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hospitals',
                'ordering': ['name'],
            },
        ),
    ]
