# Generated by Django 4.2.30 on 2026-07-09 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeathCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField()),
                ('time_of_death', models.TimeField(blank=True, null=True)),
                ('place_of_death', models.CharField(max_length=200)),
                ('age_at_death', models.PositiveIntegerField(blank=True, null=True)),
                ('cause_of_death', models.TextField()),
                ('cause_category', models.CharField(blank=True, max_length=100)),
                ('father_first_name', models.CharField(blank=True, max_length=100)),
                ('father_last_name', models.CharField(blank=True, max_length=100)),
                ('mother_first_name', models.CharField(blank=True, max_length=100)),
                ('mother_last_name', models.CharField(blank=True, max_length=100)),
                ('spouse_first_name', models.CharField(blank=True, max_length=100)),
                ('spouse_last_name', models.CharField(blank=True, max_length=100)),
                ('declarant_name', models.CharField(max_length=200)),
                ('declarant_relationship', models.CharField(max_length=100)),
                ('declarant_phone', models.CharField(blank=True, max_length=20)),
                ('declarant_id_number', models.CharField(blank=True, max_length=100)),
                ('doctor_name', models.CharField(max_length=200)),
                ('doctor_license', models.CharField(blank=True, max_length=100)),
                ('declaration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('approved', 'Validé'), ('rejected', 'Rejeté'), ('paid', 'Payé')], default='draft', max_length=20)),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('death_certificate_medical', models.FileField(blank=True, upload_to='deaths/medical/')),
                ('declarant_id_doc', models.FileField(blank=True, upload_to='deaths/ids/')),
                ('police_report', models.FileField(blank=True, upload_to='deaths/police/')),
                ('qr_code', models.ImageField(blank=True, upload_to='deaths/qr/')),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'death_certificates',
                'ordering': ['-created_at'],
            },
        ),
    ]
