# Generated by Django 4.2.30 on 2026-07-09 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deaths', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deathcertificate',
            name='declared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declared_deaths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deathcertificate',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deaths', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='deathcertificate',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_deaths', to=settings.AUTH_USER_MODEL),
        ),
    ]
