# Generated by Django 4.2.30 on 2026-07-10 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialAuthority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(help_text='Numéro de matricule officiel (ex: MAT-2024-00001)', max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text="Désactiver pour empêcher l'inscription avec ce matricule")),
                ('used_for_registration', models.BooleanField(default=False, help_text='True si ce matricule a déjà été utilisé pour créer un compte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_authority_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autorité officielle',
                'verbose_name_plural': 'Autorités officielles',
                'db_table': 'official_authorities',
                'ordering': ['matricule'],
            },
        ),
    ]
