# Generated by Django 4.2.30 on 2026-07-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_officialauthority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officialauthority',
            options={'ordering': ['matricule']},
        ),
        migrations.RemoveField(
            model_name='officialauthority',
            name='email',
        ),
        migrations.RemoveField(
            model_name='officialauthority',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='officialauthority',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='officialauthority',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='officialauthority',
            name='province',
        ),
        migrations.RemoveField(
            model_name='officialauthority',
            name='registered_user',
        ),
        migrations.RemoveField(
            model_name='officialauthority',
            name='service',
        ),
        migrations.RemoveField(
            model_name='officialauthority',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='officialauthority',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='officialauthority',
            name='matricule',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='officialauthority',
            name='used_for_registration',
            field=models.BooleanField(default=False),
        ),
    ]
